from turtle import *
from tkinter import messagebox
shape("turtle")
speed(0)
color("red","yellow")
pensize(5)
begin_fill()
for i in range(3):
    pendown()
    circle(100)
    penup()
    forward(30)
end_fill()
backward(20)
def yanxizao():
    pendown()
    begin_fill()
    for i in range(2):
        right(90)
        forward(20)
        right(90)
        forward(80)
    end_fill()
    penup()
yanxizao()
goto(xcor(),ycor()+220)
yanxizao()
goto(0,-25)
pensize(5)
def yanxizao2(bc):
    seth(270)
    pendown()
    forward(bc)
    dot(10)
    backward(bc)
    seth(0)
    penup()
    forward(15)
yanxizao2(70)
yanxizao2(90)
yanxizao2(110)
yanxizao2(90)
yanxizao2(70)
goto(15,150)
color("black")
write("元",font=("宋体雅黑",20,"bold"))
seth(270)
forward(30)
write("宵",font=("宋体雅黑",20,"bold"))
forward(30)
write("节",font=("宋体雅黑",20,"bold"))
forward(30)
write("快",font=("宋体雅黑",20,"bold"))
forward(30)
write("乐",font=("宋体雅黑",20,"bold"))
messagebox.showerror("says","结束")